//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACETAS
    {
        public int id_macetas { get; set; }
        public string descripcion { get; set; }
        public int id_semilla { get; set; }
    
        public virtual SEMILLA SEMILLA { get; set; }
    }
}
