//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbb_GudBoxEntities : DbContext
    {
        public dbb_GudBoxEntities()
            : base("name=dbb_GudBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INSTRUCCION> INSTRUCCION { get; set; }
        public virtual DbSet<MACETAS> MACETAS { get; set; }
        public virtual DbSet<OBTENCION> OBTENCION { get; set; }
        public virtual DbSet<SEMILLA> SEMILLA { get; set; }
    }
}
